<?php
// autogenerated file 24.02.2011 11:43
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * Specifies the criteria for filtering search results by location region. 
 * Different regions can be specified on different sites. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ItemLocationRegionCodeType.html
 *
 * @property string NorthAmerica
 * @property string UKIreland
 * @property string Europe
 * @property string CanadaFrench
 * @property string Canada
 * @property string Worldwide
 * @property string CustomCode
 */
class ItemLocationRegionCodeType extends EbatNs_FacetType
{
	const CodeType_NorthAmerica = 'NorthAmerica';
	const CodeType_UKIreland = 'UKIreland';
	const CodeType_Europe = 'Europe';
	const CodeType_CanadaFrench = 'CanadaFrench';
	const CodeType_Canada = 'Canada';
	const CodeType_Worldwide = 'Worldwide';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ItemLocationRegionCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ItemLocationRegionCodeType = new ItemLocationRegionCodeType();

?>
