<?php
// autogenerated file 10.09.2012 13:12
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Type defining the <b>QuantityInfo</b> container, which consists of the 
 * <b>MinimumRemnantSet</b> field, which sets the minimum amount of event tickets 
 * that canremain in the fixed-price listing's inventory after a buyer purchases 
 * one or more tickets (butnot all) from the listing. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/QuantityInfo.html
 *
 */
class QuantityInfo extends EbatNs_ComplexType
{
	/**
	 * @var int
	 */
	protected $MinimumRemnantSet;

	/**
	 * @return int
	 */
	function getMinimumRemnantSet()
	{
		return $this->MinimumRemnantSet;
	}
	/**
	 * @return void
	 * @param int $value 
	 */
	function setMinimumRemnantSet($value)
	{
		$this->MinimumRemnantSet = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('QuantityInfo', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[__CLASS__]))
				self::$_elements[__CLASS__] = array_merge(self::$_elements[get_parent_class()],
				array(
					'MinimumRemnantSet' =>
					array(
						'required' => false,
						'type' => 'int',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
